### ISSUE TITLE
Want to update List with useEffect on Page Change

### ISSUE THREAD

**Issue by dhwalin** [jepiqueau/react-datastoragesqlite-app#5] opened 2020-10-30 04:59 UTC
I have two Pages. Create Profile, List Profile.

When List Profile page loads, SQLite check whether any data is there or not. If not, code will show a message that "at least one profile needed. Please click here to create profile." & on pressing "Click Here" it will redirect user to Create Profile.

On Create Profile, when user presses Save Profile, it will redirect back to List Profile. 

But at this point, List Profile is still showing message that "At least one profile needed.", Then when I restart my App, it shows profile.

This is nothing about bug. A tip or info I want. If anyone can help. Here is my code. I am using dependency as well. 

```
const ListProfile: React.FC = () => {

  const [profileList,setProfileList] = useState([]);

  const uniqid = require('uniqid');
  const profile_id = uniqid();

  
  const {openStore, getAllKeysValues} = useStorageSQLite();

useEffect(() => { 

  async function LoadProfile(){

    
    let list_profile_result: boolean = await openStore({database:"masterdata",table:"profiles"});

   //await storage.clear();
    
    if(list_profile_result){
      let list_profile_kv:Array<string> = await getAllKeysValues();

console.log("ProfileList",list_profile_kv);

        setProfileList(list_profile_kv.map(c => JSON.parse(`${c["value"]}`)));

      
    }
    

  }

  LoadProfile();
   


},[openStore,getAllKeysValues]);
```

**Comment by jepiqueau** [comment] 2020-10-30 07:03
@dhwalin you have to give all the code for the page as i cannot see `"At least one profile needed."` With the `console.log("ProfileList",list_profile_kv);`, Did you see that the profile has been created

**Comment by dhwalin** [comment] 2020-10-30 11:50
Yes. Profiles are getting created. But I am seeking for Eventlistener if any. 

Right now after adding the profile, new profile is getting inserted in database. But It is not getting updated in State. so what happening is, code is appearing last state.

If there is 0 profile, it says to create profile.
If one profile added, on redirecting to profile list page, it shows still 0.
If second profile added, on redirecting to profile list page, it shows still 0.

Then on refreshing App / by reloading App, both profiles show.

If third profile added, only two show. Again closing App & reopening App, three profiles show.

**Comment by jepiqueau** [comment] 2020-11-01 15:43
@dhwalin  it is something wrong with the useEffect which is not updating the page this is why i was asking for the code of that page

**Comment by jepiqueau** [comment] 2020-11-01 15:49
@dhwalin Can you also give the profiles table schema

**Comment by jepiqueau** [comment] 2020-11-01 17:32
@dhwalin Looking at it a bit deeper
- getAllKeysValues() return an array of any `Array<{key: string, value: string}>`
- so i do not really understand `list_profile_kv.map(c => JSON.parse(`${c["value"]}`))`
- so if you want to have in `profileList` the list of values it should be `let profiles = list_profile_kv.map(c => c["value"]);`
- then to make sure that you update the profileList you should do `setProfileList([...profiles]);`

Hope this will help you to solve your problem

**Comment by jepiqueau** [comment] 2020-11-01 18:46
@dhwalin see example in StoreDefault.js in new release 1.0.4

**Comment by dhwalin** [comment] 2020-11-03 05:40
I have saved JSON string in Value. So ProfileList table has different keys and each key has JSON Strings.

Now in "return", I want to fetch them in loop as JSON object so I have used map and converting each entry to JSON Object from JSON String.

I have tried [...profiles] as per your example but with that setProfileList keeping all values as string only.

```
// setting profile list

let list_profile_kv:Array<string> = await getAllKeysValues();

        //setProfileList(list_profile_kv.map(c => JSON.parse(`${c["value"]}`)));
        let profiles = list_profile_kv.map(c => c["value"]);
          
        setProfileList([...profiles]);

// setting profile list

// [...profiles] output

[

"{\"id\":\"profile_kh1iwmnm\",\"profileImg\":\"capacitor://localhost/_capacitor_file_/var/mobile/Containers/Data/Application/36884AA4-3B3D-45E2-9515-2460C0BBD0AA/Documents/pfimages/kh1iweg6.jpeg\",\"firstName\":\"caca\",\"lastName\":\"affa\",\"text1\":\"\",\"text2\":\"\",\"text3\":\"\",\"text4\":\"\",\"fb\":\"\",\"ins\":\"\",\"tw\":\"\",\"wa\":\"\"}",

"{\"id\":\"profile_kh1jj9zq\",\"profileImg\":\"capacitor://localhost/_capacitor_file_/var/mobile/Containers/Data/Application/895D8F3D-B474-47BD-8727-4D161AA58112/Documents/pfimages/kh1jivfr.jpeg\",\"firstName\":\"dnnsbd\",\"lastName\":\"bsbz\",\"text1\":\"\",\"text2\":\"\",\"text3\":\"\",\"text4\":\"\",\"fb\":\"\",\"ins\":\"\",\"tw\":\"\",\"wa\":\"\"}"

]

// [...profiles] output

```
So they are object but string. So I have converted them JSON parse while fetching them. If you can provide me best solution for this, can you please let me know?

**Comment by jepiqueau** [comment] 2020-11-03 07:39
@dhwalin Look at release 1.0.5 of `https://github.com/jepiqueau/react-datastoragesqlite-app` i have had a `StoreProfiles.js` component which is doing what you want.

**Comment by jepiqueau** [comment] 2020-11-04 13:56
@dhwalin i assume not having news that the issue is solved so i close it

**Closed by jepiqueau** 2020-11-04 13:56 UTC

**Comment by dhwalin** [comment] 2020-11-05 04:14
Yes it solved. sorry I couldn’t update on this.
